### ISSUE TITLE
Proposal A discussion points

### ISSUE THREAD

**Issue by glyn** [vmware-labs/yaml-jsonpath#12]
### Applying filters to objects

Raised https://github.com/cburgmer/json-path-comparison/issues/41.

See:
* https://cburgmer.github.io/json-path-comparison/results/filter_expression_after_dot_notation_with_wildcard_after_recursive_descent.html
* https://cburgmer.github.io/json-path-comparison/results/filter_expression_after_recursive_descent.html
* https://cburgmer.github.io/json-path-comparison/results/filter_expression_on_object.html
* https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_bracket_notation_with_number_on_object.html
* https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_equals_on_object.html
* https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_value_after_recursive_descent.html

### Multiplication, division, and scripting

Raised https://github.com/cburgmer/json-path-comparison/issues/42.

See these examples where an operator is not treated as part of key:
* https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_division.html
* https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_multiplication.html

[Proposal A](https://github.com/cburgmer/json-path-comparison/tree/master/proposals/Proposal_A) lists multiplication and division as "to dos". Is this the thin end of the wedge for scripting?

### Dot notation without root

Raised https://github.com/cburgmer/json-path-comparison/issues/45.

* https://cburgmer.github.io/json-path-comparison/results/dot_notation_without_root.html

### Leading zeroes in numeric literals

Raised https://github.com/cburgmer/json-path-comparison/issues/46.

* https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_equals_number_with_leading_zeros.html

### Duplicates in filter results

Raised https://github.com/cburgmer/json-path-comparison/issues/47.

See:
* https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_equals.html
* https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_greater_than.html
* https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_greater_than_or_equal.html
* https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_less_than.html
* https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_less_than_or_equal.html
* (counter example?) https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_negation_and_equals.html

### Typo fix

Raised https://github.com/cburgmer/json-path-comparison/issues/48.

## Issues not raised

`&&` usually binds more tightly than `||` (and [seems to be the case](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence) in JavaScript), but:
* https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_different_ungrouped_operators.html

If implementors can't agree pretty unanimously that `&&` binds more tightly than `||`, then we can't expect users to expect that. So Proposal A's behaviour of failing to compile the path is a good option.

**Comment by glyn** [comment]
@cburgmer: I'd prefer to discuss the above with you before raising issues, but perhaps you'd prefer issues so that the discussion is "on the record". What do you think?

**Comment by glyn** [comment]
See https://github.com/cburgmer/json-path-comparison/tree/master/proposals/Proposal_A for some of the rationale of Proposal A.

**Comment by cburgmer** [comment]
Yes, let's discuss. 
I'd prefer to not branch out into actual implementations, but rather centralise this - quite probably over at json-path-comparison. The goal is to allow other authors to join the discussions (even if we will not capture many of the major implementations it seems).

I don't know how to structure this though. We could start with Github issues. If we find this is hard to structure, we could try moving into the wiki later.

**Comment by glyn** [comment]
All the issues have been raised.
