### ISSUE TITLE
Consider whether to support "bald" recursive descent $..

### ISSUE THREAD

**Issue by glyn** [vmware-labs/yaml-jsonpath#19]
* https://cburgmer.github.io/json-path-comparison/results/recursive_descent.html
* https://cburgmer.github.io/json-path-comparison/results/recursive_descent_after_dot_notation.html

If so, should Proposal A support this?

**Comment by glyn** [comment]
Although supporting this would make the syntax more uniform, 19 out of 37 implementations (as well as @cburgmer's Proposal A) in the comparison project return "not supported" and 4 fail when executing the query.

So, even though Goessner (JavaScript and PHP) does support `$..`, It seems that this is unlikely ever to become a consensus.

**Comment by cburgmer** [comment]
I'm documenting the decision right now:

> No consensus, but more specifically would introduce more
  complexity into grammar without much gain to the user. (We would have to
  introduce a specific terminating rule for the bald version, to avoid 
  `$...name` becoming valid.)

**Comment by glyn** [comment]
Thanks @cburgmer and good point about `$...name`.
